### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by cuongvng** [greyhub/MachineLearningProblemSets#2]
`What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).`: chưa cover trường hợp lower case (chữ thường).

**Comment by greyhub** [comment]
Cảm ơn anh. Em đã sửa 3 phần liên quan đến việc cover trường hợp lowercase:
1. `What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).`
2. `Select Employees who have name "GARY JIMENEZ.`
3. `How much does JOSEPH DRISCOLL make (including benefits)?`
